### ISSUE TITLE
关于模块【自动中断咏唱(AutoCancelCast)】的BUG（大概算是BUG？）

### ISSUE THREAD

**Issue by IceFairy520** [AtmoOmen/DailyRoutines#10]
在副本“激战城塞石卫塔”中的第二个boss，需要右键对龙弩炮，然后使用特殊技能栏向boss龙龟开炮，但打开该模块后，会导致炮击咏唱被自动取消，从而无法开炮
推测其他需要“选中友方NPC并使用其需要读条的地面设置类特殊技能”的场景都会触发此问题。
这是否算是BUG？是否有机会修复呢？

**Comment by AtmoOmen** [comment]
感谢反馈, 会进行相关测试, 如可复现, 会针对这种情况尝试优化相关逻辑以解决

**Comment by AtmoOmen** [comment]
版本 0.0.2.3 已更新, 修复了该问题
如果你在同一场景下仍然遇到了相同的问题, 请重新打开本 issue; 若出现其他问题, 请打开一个新 issue 进行反馈
