### ISSUE TITLE
[Bug]自动无人岛采集模块界面显示BUG

### ISSUE THREAD

**Issue by hakyeong** [AtmoOmen/DailyRoutines#103]
![image](https://github.com/AtmoOmen/DailyRoutines/assets/21173506/ef92a8e6-9823-41a2-840a-873bb0b2c2cd)

如图，两个按钮显示巨大，挤占了采集点信息的文本显示，重启游戏之后也还是一样

**Comment by AtmoOmen** [comment]
本地无法复现相关问题

**Comment by windandsword** [comment]
您好，在昨日晚上更新后，出现了上述同样的情况，点击按钮会导致插件和游戏崩溃，今天新增问题，点击按钮后,游戏不再崩溃，但UI文本出现了丢失，截图为今日出现的问题

![0530](https://github.com/AtmoOmen/DailyRoutines/assets/161145352/0e4711d1-abe2-43c8-820f-69542f0296bd)
![0530_1](https://github.com/AtmoOmen/DailyRoutines/assets/161145352/73a1c9ff-f63c-4d8c-bd64-7af047203c7e)

**Comment by windandsword** [comment]
> > 您好，在昨日晚上更新后，出现了上述同样的情况，点击按钮会导致插件和游戏崩溃，今天新增问题，点击按钮后,游戏不再崩溃，但UI文本出现了丢失，截图为今日出现的问题
> > ![0530](https://private-user-images.githubusercontent.com/161145352/335159330-a6a06513-da66-496c-9198-21a9c03a15eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzY1MzgsIm5iZiI6MTcxNzA3NjIzOCwicGF0aCI6Ii8xNjExNDUzNTIvMzM1MTU5MzMwLWE2YTA2NTEzLWRhNjYtNDk2Yy05MTk4LTIxYTljMDNhMTVlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxMzM3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmViMGU2NWU3ZDYyYzU4NmQ2NjNiODFiMmFkZDQ2ZGYzM2YwNGE5NTk4YWIxZjNmNjA2ZjZiYTUwZWI0NDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dA3GtNN5GydcZmOcPqZ6E-reHgbWSdsDFOaUipHQRqs) ![0530_1](https://private-user-images.githubusercontent.com/161145352/335159342-6f995528-b5a5-499b-8e6b-b6f1127287cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzY1MzgsIm5iZiI6MTcxNzA3NjIzOCwicGF0aCI6Ii8xNjExNDUzNTIvMzM1MTU5MzQyLTZmOTk1NTI4LWI1YTUtNDk5Yi04ZTZiLWI2ZjExMjcyODdjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxMzM3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzk1YTExOGQ2ZmYyNGM2M2MyZWEwYTBmMTQzN2RjZWY1N2M5NTk1M2ViZmYzYTkyMDRlMDc0NWZmOWI1NmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IDN05tElIZ13qJ_aXuu6NNSNmeJCpPb8iwbCOlYWFyc)
> 
> 请提供相关日志

抱歉，请问相关日志指的是哪些内容，方便您讲解一下吗，我好提供给您

**Comment by AtmoOmen** [comment]
> > > 您好，在昨日晚上更新后，出现了上述同样的情况，点击按钮会导致插件和游戏崩溃，今天新增问题，点击按钮后,游戏不再崩溃，但UI文本出现了丢失，截图为今日出现的问题
> > > ![0530](https://private-user-images.githubusercontent.com/161145352/335159330-a6a06513-da66-496c-9198-21a9c03a15eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzY1MzgsIm5iZiI6MTcxNzA3NjIzOCwicGF0aCI6Ii8xNjExNDUzNTIvMzM1MTU5MzMwLWE2YTA2NTEzLWRhNjYtNDk2Yy05MTk4LTIxYTljMDNhMTVlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxMzM3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmViMGU2NWU3ZDYyYzU4NmQ2NjNiODFiMmFkZDQ2ZGYzM2YwNGE5NTk4YWIxZjNmNjA2ZjZiYTUwZWI0NDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dA3GtNN5GydcZmOcPqZ6E-reHgbWSdsDFOaUipHQRqs) ![0530_1](https://private-user-images.githubusercontent.com/161145352/335159342-6f995528-b5a5-499b-8e6b-b6f1127287cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzY1MzgsIm5iZiI6MTcxNzA3NjIzOCwicGF0aCI6Ii8xNjExNDUzNTIvMzM1MTU5MzQyLTZmOTk1NTI4LWI1YTUtNDk5Yi04ZTZiLWI2ZjExMjcyODdjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxMzM3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzk1YTExOGQ2ZmYyNGM2M2MyZWEwYTBmMTQzN2RjZWY1N2M5NTk1M2ViZmYzYTkyMDRlMDc0NWZmOWI1NmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IDN05tElIZ13qJ_aXuu6NNSNmeJCpPb8iwbCOlYWFyc)
> > 
> > 
> > 请提供相关日志
> 
> 抱歉，请问相关日志指的是哪些内容，方便您讲解一下吗，我好提供给您

`/xllog` 内的

**Comment by AtmoOmen** [comment]
> 大佬我也出现相同UI问题，选择多个节点还会导致游戏崩溃，下面是我的/xllog红色部分 12:31:01.650 | ERR | [PLUGINR] PluginMaster failed: https://raw.fastgit.org/emptyset0/Radar_akira0245/master/pluginmaster.json System.Net.Http.HttpRequestException: 不知道这样的主机。 (raw.fastgit.org:443) ---> System.Net.Sockets.SocketException (11001): 不知道这样的主机。 at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context) at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped) --- End of stack trace from previous location --- at Dalamud.Networking.Http.HappyEyeballsCallback.GetSortedAddresses(String hostname, CancellationToken token) at Dalamud.Networking.Http.HappyEyeballsCallback.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken token) at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) at Dalamud.Plugin.Internal.Types.PluginRepository.GetPluginMaster(String url, Int32 timeout) at Dalamud.Plugin.Internal.Types.PluginRepository.ReloadPluginMasterAsync(Boolean skipCache) 12:31:01.981 | ERR | [PLUGINR] PluginMaster failed: https://ghproxy.com/https://raw.githubusercontent.com/Bluefissure/Penumbra/cn/repo.json System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream. at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken) at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken) at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) at Dalamud.Plugin.Internal.Types.PluginRepository.GetPluginMaster(String url, Int32 timeout) at Dalamud.Plugin.Internal.Types.PluginRepository.ReloadPluginMasterAsync(Boolean skipCache)

完全无关

**Comment by AtmoOmen** [comment]
> UI问题导致连xllog报错日志都看不到。。。 ![image](https://private-user-images.githubusercontent.com/21173506/335444141-668eedfe-9de2-40e3-80cf-15797ef2f9d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjk2MDIsIm5iZiI6MTcxNzEyOTMwMiwicGF0aCI6Ii8yMTE3MzUwNi8zMzU0NDQxNDEtNjY4ZWVkZmUtOWRlMi00MGUzLTgwY2YtMTU3OTdlZjJmOWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA0MjE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1OTRlMDM3MGM0NjFlNzdjNDAxNGUzM2NjMjA1MjY2NDk3ODFhMTM3ZDE0Y2JiMjIwNGMyYmI1MjFjZTQ2NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R-ODTWaKYnzUrVtIMz0gUn1AhgEn0OwwNVAw4oxpBPo)

可以看程序目录下 Dalamud.log 文件里

**Comment by xianggua11** [comment]
报错日志
Unhandled native exception occurred at cimgui.dll+42C23	(igTreeNodeBehavior+0x3AF7C)
Code: C0000005
Dump at: C:\Users\10148\AppData\Roaming\XIVLauncher\dalamud_appcrash_20240531_144941_399_15708.dmp
System Time: 2024-05-31 04:49:42.6881441

   at ImGuiNET.ImGuiNative.igPopStyleColor(Int32 count)

   at ImGuiNET.ImGuiNative.igPopStyleColor(Int32 count)

   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration)

   at Dalamud.Interface.Windowing.WindowSystem.Draw()

   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act)

   at Dalamud.Utility.EventHandlerExtensions.InvokeSafely(Action act)

   at Dalamud.Interface.UiBuilder.OnDraw()

   at ImGuiScene.RawDX11Scene.Render()

   at Dalamud.Interface.Internal.InterfaceManager.PresentDetour(IntPtr swapChain, UInt32 syncInterval, UInt32 presentFlags)

   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework)



Exception Info #0
Address: C0000005
Flags: 0
Address: 7FFE7EEB2C23
Parameters: 1, 21121734D08
Call Stack
{
  [0]	cimgui.dll+42C23	(igTreeNodeBehavior+0x3AF7C)
  [1]	cimgui.dll+42C23	(igTreeNodeBehavior+0x3AF7C)
  [2]	7FFE212B1B0A
}

Registers
{
  RAX:	2111F431010 [251B8470101]
  RBX:	1
  RCX:	460064
  RDX:	210DC5BC5F0 [3F170A3D00000018]
  R8:	FFFFFFFFFFFFFFEC
  R9:	0
  R10:	7FFE1F7A7740 [208A00F0148C3D29]
  R11:	7FFE21001FF0 [7FFE21305DF0]
  R12:	2
  R13:	211470C0EF0 [7FFE2016F5A8]
  R14:	8
  R15:	211470C2510 [7FFE20D26D60]
  RSI:	21103363B30
  RDI:	2110546D210 [251FAC33F30]
  RBP:	901C0FEDA0 [901C0FEED0]
  RSP:	901C0FECE8 [7FFE212B1B0A]
  RIP:	cimgui.dll+42C23	(igTreeNodeBehavior+0x3AF7C)
}

Stack
{
  [RSP+0]	7FFE212B1B0A [15473D83010C46C6]
  [RSP+8]	0
  [RSP+10]	43AF000044684000
  [RSP+18]	43AB000041E00000
  [RSP+20]	43AB000041E00000
  [RSP+28]	419FFFFF00000000
  [RSP+30]	93E571E0633E
  [RSP+38]	coreclr.dll+3FA548	(coreclr_shutdown+0x44EE8)
  [RSP+40]	901C0FF6C8 [coreclr.dll+3FA548	(coreclr_shutdown+0x44EE8)]
  [RSP+48]	7FFE1F7A7740 [208A00F0148C3D29]
  [RSP+50]	7FFE1F7A7740 [208A00F0148C3D29]
  [RSP+58]	901C0FECF0
  [RSP+60]	7FFE212B1B0A [15473D83010C46C6]
  [RSP+68]	901C0FEDA0 [901C0FEED0]
  [RSP+70]	0
  [RSP+78]	7FFE1F7A7740 [208A00F0148C3D29]
}

Modules
{
  00400000	C:\Windows\SYSTEM32\XInput1_3.dll	Microsoft Common Controller API v9.18.944.0
  59C30000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\FASMX64.dll	<no description> v1.73.16.0
  21081710000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Dalamud.dll	Dalamud v9.1.0.2
  2110F710000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.dll	System.Runtime file=v8.0.324.11423 prod=v8.0.3.0
  251B6370000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Dalamud.Common.dll	Dalamud.Common v1.0.0.0
  251B6380000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Newtonsoft.Json.dll	Json.NET .NET 6.0 file=v13.0.2.27524 prod=v13.0.2.0
  251B6440000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Threading.Thread.dll	System.Threading.Thread file=v8.0.324.11423 prod=v8.0.3.0
  251B6450000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Xml.ReaderWriter.dll	System.Xml.ReaderWriter file=v8.0.324.11423 prod=v8.0.3.0
  251B6460000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Reflection.Emit.ILGeneration.dll	System.Reflection.Emit.ILGeneration file=v8.0.324.11423 prod=v8.0.3.0
  251B6470000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Reflection.Emit.Lightweight.dll	System.Reflection.Emit.Lightweight file=v8.0.324.11423 prod=v8.0.3.0
  251B6480000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Reflection.Primitives.dll	System.Reflection.Primitives file=v8.0.324.11423 prod=v8.0.3.0
  251B6490000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Serilog.dll	Serilog v2.11.0.0
  251B64C0000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Reloaded.Hooks.dll	Reloaded.Hooks v4.2.0.0
  251B64E0000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\FFXIVClientStructs.dll	FFXIVClientStructs v1.0.0.3690
  251B6690000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Numerics.Vectors.dll	System.Numerics.Vectors file=v8.0.324.11423 prod=v8.0.3.0
  251B7670000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Serilog.Sinks.Async.dll	Serilog.Sinks.Async v1.5.0.0
  251B7680000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\netstandard.dll	netstandard file=v8.0.324.11423 prod=v8.0.3.0
  251B76A0000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Serilog.Sinks.Console.dll	Serilog.Sinks.Console v4.0.1.0
  251B76B0000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Serilog.Sinks.File.dll	Serilog.Sinks.File v5.0.0.0
  251B76C0000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.IO.FileSystem.dll	System.IO.FileSystem file=v8.0.324.11423 prod=v8.0.3.0
  251B76D0000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Text.Encoding.Extensions.dll	System.Text.Encoding.Extensions file=v8.0.324.11423 prod=v8.0.3.0
  251B76E0000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\SQLite-net.dll	SQLite-net Official .NET Standard Library v1.8.116.0
  251B7700000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\SQLitePCLRaw.core.dll	SQLitePCLRaw.core file=v2.0.4.976 prod=v2.0.4.0
  251B7720000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\SQLitePCLRaw.batteries_v2.dll	SQLitePCLRaw.batteries_v2 file=v2.0.4.976 prod=v2.0.4.0
  251B7730000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\SQLitePCLRaw.provider.dynamic_cdecl.dll	SQLitePCLRaw.provider.dynamic_cdecl file=v2.0.4.976 prod=v2.0.4.0
  251B7750000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\SQLitePCLRaw.nativelibrary.dll	SQLitePCLRaw.nativelibrary file=v2.0.4.976 prod=v2.0.4.0
  251B7760000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\ImGui.NET.dll	ImGui.NET file=v1.82.0.0 prod=v1.0.0.0
  251B77F0000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Reloaded.Memory.Buffers.dll	Reloaded.Memory.Buffers v2.0.0.0
  251B7800000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\PInvoke.Kernel32.dll	PInvoke.Kernel32 file=v0.7.104.53878 prod=v0.7.104.0
  251B7820000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\Microsoft.Win32.Primitives.dll	Microsoft.Win32.Primitives file=v8.0.324.11423 prod=v8.0.3.0
  251BB6B0000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\SharpDX.DXGI.dll	SharpDX.DXGI v4.2.0.0
  251BB6E0000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Lumina.dll	Lumina v3.16.0.0
  251BB730000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.Loader.dll	System.Runtime.Loader file=v8.0.324.11423 prod=v8.0.3.0
  251BB740000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\TerraFX.Interop.Windows.dll	TerraFX.Interop.Windows v10.0.22621.2
  251BC830000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Iced.dll	Iced v1.17.0.0
  251BCA00000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Microsoft.Extensions.ObjectPool.dll	Microsoft.Extensions.ObjectPool file=v8.0.123.58008 prod=v8.0.1.0
  251BCA10000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\ImGuiScene.dll	ImGuiScene v1.0.0.0
  251BCA50000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\CheapLoc.dll	CheapLoc file=v1.1.8.0 prod=v1.0.0.0
  251BCA60000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Diagnostics.Tracing.dll	System.Diagnostics.Tracing file=v8.0.324.11423 prod=v8.0.3.0
  251BCA70000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\HttpClient.Caching.dll	HttpClient.Caching v1.3.7.0
  251BCA80000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Reloaded.Hooks.Definitions.dll	Reloaded.Hooks.Definitions v1.14.0.0
  251BCAA0000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.CompilerServices.Unsafe.dll	System.Runtime.CompilerServices.Unsafe file=v8.0.324.11423 prod=v8.0.3.0
  251BCAB0000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Threading.ThreadPool.dll	System.Threading.ThreadPool file=v8.0.324.11423 prod=v8.0.3.0
  251BCAC0000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Threading.Overlapped.dll	System.Threading.Overlapped file=v8.0.324.11423 prod=v8.0.3.0
  251BCAD0000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.Intrinsics.dll	System.Runtime.Intrinsics file=v8.0.324.11423 prod=v8.0.3.0
  251BCAE0000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Reloaded.Memory.dll	Reloaded.Memory v7.0.0.0
  251BCB00000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Reloaded.Assembler.dll	Reloaded.Assembler v1.0.14.0
  251BCB10000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\Lumina.Excel.dll	Lumina.Excel v6.5.2.0
  251BCE80000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\System.Reactive.dll	System.Reactive file=v5.0.0.1 prod=v5.0.0.0
  251BDFC0000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Xml.XDocument.dll	System.Xml.XDocument file=v8.0.324.11423 prod=v8.0.3.0
  251C1270000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\SharpDX.dll	SharpDX v4.2.0.0
  251C12C0000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\PInvoke.User32.dll	PInvoke.User32 file=v0.7.104.53878 prod=v0.7.104.0
  251C12E0000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\SharpDX.Direct3D11.dll	SharpDX.Direct3D11 v4.2.0.0
  251C1330000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Reflection.dll	System.Reflection file=v8.0.324.11423 prod=v8.0.3.0
  251C2310000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\SharpDX.Mathematics.dll	SharpDX.Mathematics v4.2.0.0
  251C2350000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\PInvoke.Windows.Core.dll	PInvoke.Windows.Core file=v0.7.104.53878 prod=v0.7.104.0
  251C23A0000	E:\Dalamud\XIVLauncher\addon\Hooks\9.1.0.2\StbiSharp.dll	STBI C# wrapper v1.0.13.0
  251C23B0000	E:\Dalamud\XIVLauncher\runtime\shared\Microsoft.NETCore.App\8.0.3\System.Runtime.Extensions.dll	System.Runtime.Extensions file=v8.0.324.11423 prod=v8.0.3.0
  7FF6C70E0000	E:\WeGameApps\rail_apps\ffxiv(2000340)\game\ffxiv_dx11.exe	FINAL FANTASY XIV v1.0.0.0
  7FFE4CC10000	C:\Windows\Netease\Booster\ws2detour_x64.dll
