### ISSUE TITLE
游戏原生交互优化  打开后出现严重问题游戏无法运行

### ISSUE THREAD

**Issue by zflr** [AtmoOmen/DailyRoutines#104]
游戏原生交互优化 选项打开后  选完角色进入地图的时候出错崩溃 无法游戏  
自动调节屏幕亮度选项无法打开

**Comment by AtmoOmen** [comment]
请提供相关报错日志

**Comment by zflr** [comment]
[dalamud_appcrash_20240530_085733_289_2524.log](https://github.com/AtmoOmen/DailyRoutines/files/15492840/dalamud_appcrash_20240530_085733_289_2524.log)
是这个么？

**Comment by AtmoOmen** [comment]
> [dalamud_appcrash_20240530_085733_289_2524.log](https://github.com/AtmoOmen/DailyRoutines/files/15492840/dalamud_appcrash_20240530_085733_289_2524.log) 是这个么？

删除插件后重新下载即可

**Comment by zflr** [comment]
感谢大佬

**Comment by zflr** [comment]
自动屏幕亮度还是打不开呢......

**Comment by AtmoOmen** [comment]
> 自动屏幕亮度还是打不开呢......

WMI问题, 打不开就是系统不支持
