### ISSUE TITLE
[Bug] 自动重定向技能重定向后输出重复

### ISSUE THREAD

**Issue by status102** [AtmoOmen/DailyRoutines#105]
![J@1RQ611GW(AXJ5I`H1NZZQ](https://github.com/AtmoOmen/DailyRoutines/assets/102887808/282c2669-8756-416a-8d3f-a7f7dc48d71c)

**Comment by AtmoOmen** [comment]
是因为按了多次然后重复提示了多次还是单独按了一次也报了多次？

**Comment by AtmoOmen** [comment]
fixed in https://github.com/AtmoOmen/DailyRoutines/releases/tag/0.5.1.0
