### ISSUE TITLE
[Bug] 自動批量完成生產理符國際服無法運作

### ISSUE THREAD

**Issue by Hartmann1003** [AtmoOmen/DailyRoutines#107]
前置模塊都有開 但沒辦法運作 上個版本還能正常運作
![014301](https://github.com/AtmoOmen/DailyRoutines/assets/145864080/70ee6654-b39c-4f10-929d-b325d51b71c6)

**Comment by AtmoOmen** [comment]
精力有限，不对国际服提供支持
