### ISSUE TITLE
第一艘潜艇动画无法跳过

### ISSUE THREAD

**Issue by cyf5119** [AtmoOmen/DailyRoutines#11]
第一艘潜艇出发的动画无法跳过，但后面三艘可以，后面三艘的自动收艇也正常运行。
还未排除出是否由其他插件引起。
图中，绿线以上为收第一艘艇时出现的报错，绿线以下为手动跳过第一艘艇动画后再次点击开始按钮后的报错。
![Snipaste_2024-02-22_23-26-31](https://github.com/AtmoOmen/DailyRoutines/assets/89454904/0b68fd56-e0cc-4255-bb88-bda5ddeeeebf)

**Comment by AtmoOmen** [comment]
这问题延续了好多个小版本了，看着代码都没啥问题但是不知道为啥第一艘潜艇动画跳不过，再加上一天就能测试一次所以修复可能需要缘分

**Comment by AtmoOmen** [comment]
尝试优化了相关逻辑，现已可以正常跳过第一艘潜艇的过场动画，将在下次版本更新时放出
至于空引用报错, 则是 ECommons 的问题, 不做解决的尝试

**Comment by cyf5119** [comment]
感谢！
