### ISSUE TITLE
【自动批量完成生产理符】配置完成并点击开始后无效果

### ISSUE THREAD

**Issue by QwQry** [AtmoOmen/DailyRoutines#111]
配置完成并点击开始后 直接提示 “批量提交理符任务已完成”  但人物没有动作 理符额度也还有剩余 确认3个前置模块均已打开 任务提交道具也在背包里
![Uploading {26E7041D-274D-4156-B6FF-272D342AFCCE}.png…]()

**Comment by AtmoOmen** [comment]
请提供插件版本
