### ISSUE TITLE
丢弃每次只丢一个

### ISSUE THREAD

**Issue by 996zhishi** [AtmoOmen/DailyRoutines#112]
在一个丢弃小组内设置了5种物品，但每次只丢其中一种便没有反应，过一会就自动停止了。需要自己来回开启停止才能丢完一个小组内设置的物品。
请问是否需要前置插件还是出现了别的问题？
版本：0.5.1.0

**Comment by AtmoOmen** [comment]
请先检查是否有其他插件干扰模块运行

**Comment by 996zhishi** [comment]
好的谢谢，经排查是跟yes的插件冲突
