### ISSUE TITLE
游戏崩溃相关

### ISSUE THREAD

**Issue by shellouo** [AtmoOmen/DailyRoutines#113]
看到卫月给的报错信息大概是：
Unhandled native exception occurred at KERNELBASE.dll+2CF19 (RaiseException+0x69)
Code: E0434352
Dump at: F:\FF14 Kit\XIVLauncherCN\Roaming\addon\Hooks\9.1.0.2........\Roaming\dalamud_appcrash_20240608_004526_994_25268.dmp
System Time: 2024-06-07 16:45:27.4749422

at DailyRoutines.Helpers.LuminaCache.TryGetAndCacheSheet[T](ExcelSheet`1& sheet)

at DailyRoutines.Helpers.LuminaCache.TryGetRow[T](UInt32 rowID, T& item)

at DailyRoutines.Managers.LogMessageManager.OnReceiveLogMessages(UInt32 logMessageID)

at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework)
是我操作不当吗

**Comment by AtmoOmen** [comment]
请提供更加详细的信息，比如崩溃发生时正在进行什么操作

**Comment by shellouo** [comment]
我是使用了如下功能（1.自动登录2.自动批量完成生产理符3.自动防技能重复4.自动跳舞5.自动最优队员推荐6.自动精致魔晶石7.自动确认任务结果8.自动跳过对话9.自动选择并递交物品）
昨天登录时候忽然发现自动登录功能没有启用，起初没有在意，登录后走几步路就游戏就卡死卫月弹窗说游戏崩了，重复登录也是走几步就卡死。于是我看了下dailyroutines里面自动登录的设置，发现虽然登录信息显示有一条登录数据，但是打开下拉框发现服务器名消失了，按下“当前服务器”按钮也无法获取当前服务器。之后我将dailyroutines插件关闭就不再闪退。

**Comment by zflr** [comment]
[dalamud_appcrash_20240621_222944_806_12256.log](https://github.com/user-attachments/files/15929049/dalamud_appcrash_20240621_222944_806_12256.log)
崩溃

**Comment by AtmoOmen** [comment]
> [dalamud_appcrash_20240621_222944_806_12256.log](https://github.com/user-attachments/files/15929049/dalamud_appcrash_20240621_222944_806_12256.log) 崩溃

和 DR 完全无关
