### ISSUE TITLE
插件部分功能会导致右键道具菜单出现残留选项

### ISSUE THREAD

**Issue by msew11** [AtmoOmen/DailyRoutines#117]
使用完雇员的`自动道具合并递交`，退出雇员。右键任一道具，菜单会残留一个选项。点击后会900002。
![image](https://github.com/AtmoOmen/DailyRoutines/assets/23654758/2740461b-e6de-4ded-9bf6-ab12784ee560)

**Comment by AtmoOmen** [comment]
无法复现，即使复现也无法修复
