### ISSUE TITLE
雇员降价可接受最大降价数值逻辑有误，只能关掉使用

### ISSUE THREAD

**Issue by cwpshuaige** [AtmoOmen/DailyRoutines#12]
雇员降价可接受最大降价数值逻辑有误，只能关掉使用，不管设置多少都显示超过最大可接受降价数值

**Comment by AtmoOmen** [comment]
感谢反馈, 已确认为相关判断逻辑中 最大可接受降价值 变量被误写为了 最低可接受价格 变量
该问题将在下一版本中进行修复

**Comment by cwpshuaige** [comment]
还有就是，既然已经有了一键精炼魔晶石，希望可以加一个一键精选灵砂的功能（orz

**Comment by AtmoOmen** [comment]
> 还有就是，既然已经有了一键精炼魔晶石，希望可以加一个一键精选灵砂的功能（orz

在即将到来的 6.5 版本, SE已经追加了连续精选功能, 就不重复写了
