### ISSUE TITLE
只装了中文字体mod，部分卫月插件无法正常显示中文。

### ISSUE THREAD

**Issue by kanzakiken** [AtmoOmen/DailyRoutines#122]
之前一直都是通过覆盖文件的方式装的汉化，卫月插件可以正常显示中文字体。
现在把汉化包去掉了，然后只用Penumbra装了中文字体的mod。但是发现部分卫月插件无法正常显示中文。
请问可以通过覆盖游戏文件的方式，只装中文字体，不汉化游戏文本吗？如果可以的话，需要覆盖哪个文件。
求大佬指导。

**Comment by AtmoOmen** [comment]
问题与插件不相关，插件也不对国际服提供支持

**Comment by kanzakiken** [comment]
> 问题与插件不相关，插件也不对国际服提供支持

抱歉大佬，我提错地方了，本来想在国际服汉化那里提issue的，开了好几个网页，切换错了，实在抱歉。
