### ISSUE TITLE
0.5.3.3 更新后取消了我之前勾选的跳过主随动画

### ISSUE THREAD

**Issue by pingmoogle** [AtmoOmen/DailyRoutines#126]
![image](https://github.com/AtmoOmen/DailyRoutines/assets/33149289/fcb09236-346c-4f34-92ad-507f80f6e8a5)

之前这个选项是“自动跳过主随动画”，我一直都打开的
更新之后变成了“自动跳过副本过场动画”，并且默认取消了

建议是：
1. 更新功能时，请保留用户已有的配置
2. 对于新功能，建议增加新配置项，而不是修改已有的配置项（可能有人就是只想跳主随动画，但是不想跳其他动画呢）

谢谢作者的高强度更新！以上建议望考虑！

**Comment by AtmoOmen** [comment]
实际流程是: 删除旧模块, 新增新模块。因此会出现你提到的情况, 因为本身就是不一样的模块。
关于配置, 更新或者重构时一直在采取尽可能留存用户旧配置的策略, 但肯定会涉及到前后版本难以兼容的问题, 而整个插件绝大部分模块、所有功能和主体框架都是我一个人独立维护的, 因此受限于精力, 很多时候面对破坏性变更时, 我是无力写旧版配置解析器的。
最后, 关于为什么旧模块删除了, 可以简单把原因理解为避嫌, 采取了完全不同的自动处理过场剧情跳过的逻辑。
