### ISSUE TITLE
跳动画bug

### ISSUE THREAD

**Issue by HNDXlsp** [AtmoOmen/DailyRoutines#13]
无法跳过部队工坊动画，我在搓潜水艇的时候发现了这个问题，有时候还会看完动画还会有esc界面

**Comment by AtmoOmen** [comment]
会尝试复现场景, 若复现成功会着手解决, 但修复会延迟到国服 6.5 更新后统一更新

**Comment by HNDXlsp** [comment]
是不是检测屏蔽词的正则问题，1101+0020*3 一打出来就卡死 游戏直接未响应，我确定是这个插件的问题

**Comment by AtmoOmen** [comment]
> 是不是检测屏蔽词的正则问题，1101+0020*3 一打出来就卡死 游戏直接未响应，我确定是这个插件的问题

插件不使用正则检测屏蔽词, 只调用国服客户端原生的屏蔽系统处理文本

**Comment by AtmoOmen** [comment]
0.0.2.7 已采取了新的跳过过场动画逻辑，屏蔽词相关的问题也已经处理完成
如果你遇到了同样的问题, 请重新打开该 issue
如果你遇到了新的问题, 请打开一个新 issue
