### ISSUE TITLE
[Feature Request] 招募相关功能

### ISSUE THREAD

**Issue by msew11** [AtmoOmen/DailyRoutines#137]
1.增加一个依附于游戏UI的设置界面（可以配置自动刷新，招募过滤等招募相关的功能，类似雇员相关功能）
2.增加特定副本的过滤（目前好像只支持招募人或描述的过滤）
3.如果游戏在后台，自动刷新出现匹配过滤的招募，发送一条Windows系统通知（适用场景：可以切后台做其他事情，不用时刻关注，招募出现自动提醒）

**Comment by status102** [comment]
1. 自动刷新有，但是目前疑似有bug且难以稳定复现
2.3. betterParryFinder已实现
