### ISSUE TITLE
希望能添加自动分解功能

### ISSUE THREAD

**Issue by IceFairy520** [AtmoOmen/DailyRoutines#14]
如题，就像自动精致魔晶石功能在精制魔晶石界面添加一个开始/停止的小窗一样，能否在分解界面也加一个自动分解呢？这样方便处理打本掉的装备

**Comment by AtmoOmen** [comment]
可以, 会考虑在后续版本添加

**Comment by AtmoOmen** [comment]
已在 0.0.2.8 版本 中加入
