### ISSUE TITLE
‘自动切换输入法’ 的优化可能

### ISSUE THREAD

**Issue by aurorataro** [AtmoOmen/DailyRoutines#146]
原生游戏时，按下``/``在聊天框输入指令，输入法会自动切换为英文方便指令输入。
开启此插件并选择中文输入法（sogou）后原有的特性被覆盖，对于直接输入英文指令变得更加繁琐（需要切换一次）。
希望可以优化这个问题，感谢。

**Comment by AtmoOmen** [comment]
游戏输入机制限制，无法在焦点的瞬间获取到输入内容，实现相关内容需要涉及不稳定操作，短时间内不考虑
