### ISSUE TITLE
关于自动雇员改价时处理位于不同雇员出售列表的同种物品时的问题

### ISSUE THREAD

**Issue by IceFairy520** [AtmoOmen/DailyRoutines#15]
该模块在改价时，如果同一种物品在不同的雇员出售，会出现自己压自己价的情况
例如，物品x的当前市场价为1000，自动改价设置单次压价20，将物品x分为两份 ，先在雇员A出售第一份，会自动设置售价为980，但在雇员B出售第二份时，会售价会被设置为960
这是否可以被修复？即改价时忽略市场上自己的其他雇员在售的同种物品的价格

**Comment by AtmoOmen** [comment]
可以, 会在后续版本加入相关的判断逻辑

**Comment by AtmoOmen** [comment]
尝试以优化逻辑的方法在 0.0.2.8 版本解决了该问题

如果你遇到了同样的问题, 请重新打开该 issue
如果你遇到了新的问题, 请打开一个新 issue
