### ISSUE TITLE
关于6.5版本雇员压价的问题

### ISSUE THREAD

**Issue by nandehututu** [AtmoOmen/DailyRoutines#17]
新6.5版本更新后，雇员压价里勾选区分nq和hq后，获取的hq价格是上一个物品nq的价格，无法正确识别当前物品hq价格，麻烦修改下bug，十分感谢您的即时更新6.5
![QQ图片20230911145234](https://github.com/AtmoOmen/DailyRoutines/assets/43106687/28aa537a-8501-44ba-8745-8244f5f7643c)

**Comment by nandehututu** [comment]
![QQ截图20240307090556](https://github.com/AtmoOmen/DailyRoutines/assets/43106687/33bb782a-831a-47bb-9cab-1bffe8f09fd2)尴尬 发错图了，补张图

**Comment by AtmoOmen** [comment]
会对该问题进行查验核实，感谢反馈

**Comment by AtmoOmen** [comment]
尝试以优化逻辑的方法在 0.0.2.8 版本修复了该问题

如果你遇到了同样的问题, 请重新打开该 issue
如果你遇到了新的问题, 请打开一个新 issue
