### ISSUE TITLE
关于自动压价的另一个小bug

### ISSUE THREAD

**Issue by nandehututu** [AtmoOmen/DailyRoutines#19]
谢谢您及时修改关于自动压价的bug，我又发现另一个小bug。版本：v0.0.2.8
商店弹出框子的时候，假如网络有一定延迟，商店价格的数据会有一定的延迟，造成商店框子弹出来👉商店数据还没弹出👉商店框子就被关掉了的现象。然后就获取了个0元的数据。

**Comment by nandehututu** [comment]
![QQ截图20240307164314](https://github.com/AtmoOmen/DailyRoutines/assets/43106687/324f48d8-74a1-49c5-8a26-ef412251d513)
111111111

**Comment by A2uria** [comment]
应该是在开启区分 hq 的情况下 nq 能正常获取市场价而 hq 不行。

**Comment by AtmoOmen** [comment]
已重新推送 0.0.2.8 版本, 请删除本地插件后重新下载, 应该可以解决问题
