### ISSUE TITLE
模块："自动精制魔晶石"，未正常工作

### ISSUE THREAD

**Issue by Souma-Sumire** [AtmoOmen/DailyRoutines#20]
## 环境
- 国服 6.5
- 插件版本 v0.0.2.8 （仅启用这一个模块）

## 复现
- 点击 `开始`
- 第一个物品精炼完成
- 列表变为空
- 程序继续“精炼”
- 系统跳出错误 `剧情被中断` 
- 循环以上2步

https://github.com/AtmoOmen/DailyRoutines/assets/33572696/034957a2-f3f4-4d2c-b7ec-758b8d23b285

**Comment by AtmoOmen** [comment]
6.5 国服精制界面似乎存在很多问题, 已更换相关自动化的实现方式, 将会在下次更新推送时修复, 感谢反馈!

**Comment by AtmoOmen** [comment]
0.0.2.9 版本已推送

如果你遇到了同样的问题, 请重新打开该 issue
如果你遇到了新的问题, 请打开一个新 issue
