### ISSUE TITLE
希望理符功能能添加特定的钓鱼理符

### ISSUE THREAD

**Issue by uniofore** [AtmoOmen/DailyRoutines#21]
比如80级钓鱼理符黑色三连星。这是最快的采集理符成就完成方法了。

**Comment by AtmoOmen** [comment]
已加入, 将在下次版本更新时推送

**Comment by AtmoOmen** [comment]
0.0.2.9 版本已推送

如果你遇到了同样的问题, 请重新打开该 issue
如果你遇到了新的问题, 请打开一个新 issue
