### ISSUE TITLE
能否添加舞者自动跳舞功能

### ISSUE THREAD

**Issue by IceFairy520** [AtmoOmen/DailyRoutines#22]
设想是按下大/小舞后自动正确完成舞步，再加个可选子选项：完成舞步后自动使用舞步结束

**Comment by AtmoOmen** [comment]
可以, 很简单, 下个版本会加上

**Comment by AtmoOmen** [comment]
0.0.2.9 版本已推送

如果你遇到了同样的问题, 请重新打开该 issue
如果你遇到了新的问题, 请打开一个新 issue
