### ISSUE TITLE
自动雇员改价获取价格为0

### ISSUE THREAD

**Issue by LeiSangSang** [AtmoOmen/DailyRoutines#25]
[10:13][Daily Routines]物品: 第四期重建用的特供冰笋（检） (当前市场价: 0 / 原价: 95) 已低于设定最低价: 30, 跳过改价

开始是正常的,但似乎是获取到的一整页出售记录都是自己的雇员的时候开始获取到的当前市场价就是0了

**Comment by AtmoOmen** [comment]
下个版本会针对这种情况加一个 fallback

**Comment by AtmoOmen** [comment]
0.0.3.0 版本已推送, 请注意：对 HQ 物品的判别仍然依赖于 UI 界面, 因此仍然会受到游戏 UI 所设定的 10 个物品限制

如果你遇到了同样的问题, 请重新打开该 issue
如果你遇到了新的问题, 请打开一个新 issue
