### ISSUE TITLE
自动收取潜水艇的修理问题和ui问题

### ISSUE THREAD

**Issue by HeavenPolicy** [AtmoOmen/DailyRoutines#26]
潜艇在自动修理时会有部件修理不上后无法出发的情况，并且会将ui卡掉消失无法进行操作，只能退游戏重进。已经关掉yesalready
附日志

00:00:19.885 ERR | [DailyRoutines] Object reference not set to an instance of an object.
00:00:19.885 ERR |    at ECommons.Automation.TaskManager.Tick(Object _) in D:\young\Documents\GitHub\DailyRoutines\ECommons\ECommons\Automation\TaskManager\TaskManager.cs:line 145
00:00:19.889 DBG | [DailyRoutines] Starting to execute task: ReadyToRepairSubmarines
00:00:20.318 INF | [Collections] DresserObserver->LoadDresserContents: Refreshing Dresser contents count: 726 -> 726
00:00:22.971 VRB | WindowSystem "DailyRoutines" Window "Daily Routines - Main" lost focus
00:00:23.048 DBG | [AetheryteLinkInChat] Command: /xllog
00:00:25.320 INF | [Collections] DresserObserver->LoadDresserContents: Refreshing Dresser contents count: 726 -> 726
00:00:30.320 INF | [Collections] DresserObserver->LoadDresserContents: Refreshing Dresser contents count: 726 -> 726
00:00:35.324 INF | [Collections] DresserObserver->LoadDresserContents: Refreshing Dresser contents count: 726 -> 726
00:00:40.326 INF | [Collections] DresserObserver->LoadDresserContents: Refreshing Dresser contents count: 726 -> 726
00:00:45.329 INF | [Collections] DresserObserver->LoadDresserContents: Refreshing Dresser contents count: 726 -> 726
00:00:49.905 WRN | [DailyRoutines] Clearing 0 remaining tasks because of timeout
00:00:49.906 WRN | [DailyRoutines] Task ReadyToRepairSubmarines took too long to execute
00:00:49.906 WRN |    at ECommons.Automation.TaskManager.Tick(Object _) in D:\young\Documents\GitHub\DailyRoutines\ECommons\ECommons\Automation\TaskManager\TaskManager.cs:line 158

**Comment by AtmoOmen** [comment]
日志中没有什么有效信息, 潜水艇模块还是一如既往地修复随缘, 每日能测试的机会太少, 而且我本地也没有办法复现相关问题
目前已经尝试重构了潜水艇修理逻辑, 等待测试中。

**Comment by HeavenPolicy** [comment]
经过部分测试，复现出的结果如下：
关闭dailiy插件的自动跳过对话/自动跳过过场动画/等基础部分的所有选项，打开textadvance插件默认模式。开关yesalready均不影响结果。
只打开daily插件的‘自动收取潜水艇’部分，不点击开始键，只使用插件自带的半辅助收艇功能。在跳出“上次的远航报告”→旅程报告→自动跳出再次出发，显示航线的界面后点击‘取消’键或按esc键后，潜水艇界面会整个消失，无法回到“旅程报告”界面，并且无法行走，无法退出游戏，无法返回标题画面。
简单描述的话则是，如果在开启插件期间不小心手滑点击了“上次的远航报告”界面，无论点击取消还是使用esc关闭界面，都必定会卡住潜水艇界面的ui。
在任务栏内右键最终幻想14的图标点击关闭后，游戏内会跳出“确定要退出游戏吗”的对话框，此时点击“是”可以退出游戏，在游戏界面消失的一瞬间可以看到“旅程报告”界面。
在关闭“自动收取潜水艇”功能时可以正常点击“上次的远航报告”按钮，暂时未发现界面整个卡住消失的情况

**Comment by HeavenPolicy** [comment]
修理日进行了一些测试，点击“上次的远航报告”时不再有卡ui的问题，但这次修理时发生了弹出修理界面后游戏崩溃的情况。不点击开始按钮进行自动收艇的话则正常

**Comment by AtmoOmen** [comment]
国服 FFCS 的问题, 会想办法绕开

**Comment by AtmoOmen** [comment]
国服 FFCS 的问题, 会想办法绕开

**Comment by AtmoOmen** [comment]
0.0.3.1 版本已推送
