### ISSUE TITLE
希望可以让每种功能有单独的指令，以在对话框中执行

### ISSUE THREAD

**Issue by HeavenPolicy** [AtmoOmen/DailyRoutines#3]
现在每次执行功能（如潜水艇插件）需要点开插件界面后手动点击开始，希望可以加入/指令来省略反复点开插件界面的步骤

**Comment by AtmoOmen** [comment]
请先尝试使用 /pdr 用指令打开插件界面，至于指令操作模块流程，需要评估一下可操作性和一些代码规范
