### ISSUE TITLE
潜水艇修理的时候概率会崩溃呀

### ISSUE THREAD

**Issue by SmoothShadow** [AtmoOmen/DailyRoutines#30]
![QQ截图20240316135047](https://github.com/AtmoOmen/DalamudPlugins/assets/72059086/4032d5be-911c-427b-a262-24a174c05b66)

**Comment by SmoothShadow** [comment]
你好,昨晚的日志找不着了,这是我刚刚收艇显示的错误,希望能对定位错误有些帮助

这是报错之后保存的.log文件
Unhandled native exception occurred at ffxiv_dx11.exe+5ADF3
Code: C0000005
Dump at: C:\Users\

这是dalamud的日志:
2024-03-16 18:00:46.032 +08:00 [ERR] [DailyRoutines] Object reference not set to an instance of an object.
   at ECommons.Automation.TaskManager.Tick(Object _) in D:\young\Documents\GitHub\DailyRoutines\ECommons\ECommons\Automation\TaskManager\TaskManager.cs:line 145

**Comment by AtmoOmen** [comment]
你发的日志里面没有任何有效信息

**Comment by SmoothShadow** [comment]
我挺想把详细的日志发上来可是这里好像只能上传图片文件呀,不过既然你可以正常使用的话也许是跟哪个插件冲突了吧,回头我挨个排查一下

**Comment by nvidiamd** [comment]
> 我挺想把详细的日志发上来可是这里好像只能上传图片文件呀,不过既然你可以正常使用的话也许是跟哪个插件冲突了吧,回头我挨个排查一下

我也是 更新后就会崩溃了 在排查中 就修理的时候会崩溃

**Comment by SmoothShadow** [comment]
> > 我挺想把详细的日志发上来可是这里好像只能上传图片文件呀,不过既然你可以正常使用的话也许是跟哪个插件冲突了吧,回头我挨个排查一下
> 
> 我也是 更新后就会崩溃了 在排查中 就修理的时候会崩溃

你安装yesAlready和textAdvanced了吗? 我小号关了这两个成功修理了,不知道是不是这两个插件的原因

**Comment by AtmoOmen** [comment]
0.0.3.1 版本已推送

**Comment by nvidiamd** [comment]
> > > 我挺想把详细的日志发上来可是这里好像只能上传图片文件呀,不过既然你可以正常使用的话也许是跟哪个插件冲突了吧,回头我挨个排查一下
> > 
> > 
> > 我也是 更新后就会崩溃了 在排查中 就修理的时候会崩溃
> 
> 你安装yesAlready和textAdvanced了吗? 我小号关了这两个成功修理了,不知道是不是这两个插件的原因,明天我再试试

我昨天也是关了这俩就好了 今天更新了 可以直接在潜水艇界面点收艇了 开着插件也没报错
