### ISSUE TITLE
0.0.3.1版本理符功能失效？

### ISSUE THREAD

**Issue by sawatarishinko** [AtmoOmen/DailyRoutines#31]
帮朋友问的 我本人还没更新 还是0.0.3.0 一切正常

https://github.com/AtmoOmen/DailyRoutines/assets/59863893/9b8cac89-f7f4-4ebf-98ca-ed30d602bb1b

**Comment by AtmoOmen** [comment]
本地一切正常, 而且理符模块的逻辑已经有四五个小版本没有动过了

**Comment by sawatarishinko** [comment]
那我让他自己想办法解决
