### ISSUE TITLE
希望自动防技能重复能添加防重复复活功能

### ISSUE THREAD

**Issue by IceFairy520** [AtmoOmen/DailyRoutines#33]
众所周知，重复拉人是一件非常蛋疼的事情，如果能把复活状态也加进去对拉人职业来说就太好了

**Comment by IceFairy520** [comment]
以及其他各类团辅，例如舞者的，身上有技巧舞步结束时防止跳大舞，忍者的目标身上有背刺时防止按夺取，龙骑有战斗连祷防止按连祷，诗人有战斗之声防止按战斗之声等_(:з」∠)_

**Comment by AtmoOmen** [comment]
除了复活之外, 一开始是因为想着会影响循环就没加进去, 后来去写其他插件就忘了, 下版本会加上

**Comment by AtmoOmen** [comment]
0.0.3.3 版本已推送
