### ISSUE TITLE
`自动批量完成生产理符`在理符委托人有其他未完成理符时无法连续接取理符

### ISSUE THREAD

**Issue by status102** [AtmoOmen/DailyRoutines#36]
当提交NPC头上挂了其他礼服未完成时，无法触发第二次自动接取，而是超时结束

**Comment by AtmoOmen** [comment]
0.0.3.4 版本已推送

如果你仍然遇到相同的问题, 请重新打开本 issue
如果遇到了其他方面的问题, 请打开一个新 issue

**Comment by status102** [comment]
0.0.3.4 确认无复现，但是有时候会卡在自动交物品这里
![image](https://github.com/AtmoOmen/DailyRoutines/assets/102887808/79b23588-7dca-4e56-8fa1-9d9c58f027e8)

已选择但是未确定

**Comment by AtmoOmen** [comment]
> 0.0.3.4 确认无复现，但是有时候会卡在自动交物品这里 ![image](https://private-user-images.githubusercontent.com/102887808/317943933-79b23588-7dca-4e56-8fa1-9d9c58f027e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODY1NTcsIm5iZiI6MTcxMTY4NjI1NywicGF0aCI6Ii8xMDI4ODc4MDgvMzE3OTQzOTMzLTc5YjIzNTg4LTdkY2EtNGU1Ni04ZmExLTlkOWM1OGYwMjdlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwNDI0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzBhNWJkZjFkN2NhMjFmNGEzZGI3MWMzNTRlYzdiYjkzNWE4OThiZDI2ZDBkNjQxOWU0YzJkZDU5Y2E5OTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ILGBxpYdcfsJPhv_kFuHXwGMfzafYQm6evArurkBq-E)
> 
> 已选择但是未确定

仍然无法复现, 看上去是前置模块的问题
