### ISSUE TITLE
是否能加入定期尝试进入新频选项

### ISSUE THREAD

**Issue by PinkYuDeer** [AtmoOmen/DailyRoutines#37]
![image](https://github.com/AtmoOmen/DailyRoutines/assets/83949453/a61423eb-0f1a-45c1-8b8d-2d5486d1fa9d)
点开自动登录选项后如图所示，下面选项消失，也无法输入名字。

p.s.自动加入新频可不可以增加一个新的选项，勾选之后可以在没有进入新频的时候隔一段时间就尝试进入一次？我很需要这个，爱来自瓷器

**Comment by A2uria** [comment]
https://github.com/AtmoOmen/DailyRoutines/blob/33d85425f89a8b46e146fc500047b3e804b1c2e9/DailyRoutines/Modules/General/AutoLogin.cs#L56-L57

![image](https://github.com/AtmoOmen/DailyRoutines/assets/83493416/7a60ed70-5de2-4722-8b1a-dcf74c07b5fa)

![image](https://github.com/AtmoOmen/DailyRoutines/assets/83493416/a6debfdc-f558-4477-a6ba-55da8f722df4)

WorldInput 空引用？

**Comment by AtmoOmen** [comment]
> https://github.com/AtmoOmen/DailyRoutines/blob/33d85425f89a8b46e146fc500047b3e804b1c2e9/DailyRoutines/Modules/General/AutoLogin.cs#L56-L57
> 
> ![image](https://private-user-images.githubusercontent.com/83493416/317641059-7a60ed70-5de2-4722-8b1a-dcf74c07b5fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTMyMDMsIm5iZiI6MTcxMTYxMjkwMywicGF0aCI6Ii84MzQ5MzQxNi8zMTc2NDEwNTktN2E2MGVkNzAtNWRlMi00NzIyLThiMWEtZGNmNzRjMDdiNWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA4MDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZmNjMTk4MDc0MTNmYzkwODNiZDc1NTFhNGQ0ZmZlMmUwMTJhMTkxNGNiMTQ4OWVjNTZlYjdkMjhiY2I1NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Blu-UlymuqxETjEN9kIBNrCdWnKmX2YVRTXx07CH3ok)
> 
> ![image](https://private-user-images.githubusercontent.com/83493416/317641488-a6debfdc-f558-4477-a6ba-55da8f722df4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTMyMDMsIm5iZiI6MTcxMTYxMjkwMywicGF0aCI6Ii84MzQ5MzQxNi8zMTc2NDE0ODgtYTZkZWJmZGMtZjU1OC00NDc3LWE2YmEtNTVkYThmNzIyZGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA4MDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MDk0NDNmYzk0NTUzMGRkZjA5NDY0NThmZTgxYjg5M2QzODYyODZmODI2OTI0MmQ2MDQyMmUxMWIwZTc1OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2f5LTMswzkhIKPG5utE4B9j9iiN0ArEfeKlvqp90VcY)
> 
> WorldInput 空引用？

emmm, 如果是空引用的话有可能是这里

https://github.com/AtmoOmen/DailyRoutines/blob/33d85425f89a8b46e146fc500047b3e804b1c2e9/DailyRoutines/Modules/General/AutoLogin.cs#L40

**Comment by A2uria** [comment]
![image](https://github.com/AtmoOmen/DailyRoutines/assets/83493416/8c703c5f-bd8b-4fda-8136-dff7a9c29428)

修好了。

**Comment by AtmoOmen** [comment]
0.0.3.5 已推送
