### ISSUE TITLE
在使用命令/pdr+搜索内容时出现的问题

### ISSUE THREAD

**Issue by PinkYuDeer** [AtmoOmen/DailyRoutines#40]
我在最新的版本（0.0.3.5）中，使用（/pdr 雇员）和（/pdr 跳过）来尝试快速的切换跳过选项和使用雇员相关功能，这个指令确实打开了配置界面并且显示出了搜索结果。但是无论如何我点击前面的对钩都不起作用。 刚刚又重复测试了一下，发现搜索内容中的第一项可以正常开启或关闭，其余搜索项目既不能将之开启，也不能关闭。

**Comment by PinkYuDeer** [comment]
顺带一提，我这次更新（从0.0.3.41）是删除后重新下载的方式，本来推测是更新没有推送，但是刚才忽然想到或许是因为5小于41的缘故，让此次更新无法直接覆盖更新。

**Comment by AtmoOmen** [comment]
搜索功能会检查一下代码,
至于版本号这个是月的问题, 我没办法.jpg
只能以后手动避免0.0.0.xx这样的版本号了

**Comment by AtmoOmen** [comment]
0.3.6.0 版本已推送
