### ISSUE TITLE
[游戏日历]可以每次进入游戏就弹出就好了

### ISSUE THREAD

**Issue by stlion** [AtmoOmen/DailyRoutines#48]
游戏日历功能很实用，希望可以更进一步，让每次进入游戏就弹出游戏日历，提醒玩家。

或者，让DailyRoutines可以自定义打开时优先显示的标签页，每次打开第一眼就是游戏日历。

**Comment by AtmoOmen** [comment]
下版本会以登录后发送聊天消息的形式提供, 默认关闭, 需要在设置中开启

**Comment by AtmoOmen** [comment]
0.3.8.0 已推送
