### ISSUE TITLE
希望可以增加法奶打开自动攻击的功能

### ISSUE THREAD

**Issue by PinkYuDeer** [AtmoOmen/DailyRoutines#49]
在玩法系和奶妈的时候，只能通过手动右键、或者将共通技能中的自动攻击拖在技能栏上点击，
然后再切换目标或者目标丢失后，自动攻击的状态就会失去，需要重新点击，这令我十分的难过。

我猜想是否可以通过检测当前状态是不是自动攻击，来自动化打开自动攻击的过程。
![image](https://github.com/AtmoOmen/DailyRoutines/assets/83949453/2c2134a3-eee1-416f-92d9-fc7cca3f65bd)

**Comment by AtmoOmen** [comment]
已添加, 将在下个版本推送

**Comment by PinkYuDeer** [comment]
义父，你是我的神

**Comment by AtmoOmen** [comment]
0.3.8.0 已推送
