### ISSUE TITLE
自动雇员改价不区分hq和nq物品

### ISSUE THREAD

**Issue by EzakiRinko** [AtmoOmen/DailyRoutines#5]
如题 我卖HQ材料时 自动改价取的是NQ的最低价格

**Comment by AtmoOmen** [comment]
已加入待办事项, 会在评估完可行性并测试完成后添加

**Comment by AtmoOmen** [comment]
0.0.1.7 已更新, 此功能已包含在更新内, 后续如若在此功能上发现任何问题, 请打开一个新 Issue
