### ISSUE TITLE
ExpandPlayerMenuSearch的配置文件的字段错误的都保存成石之家

### ISSUE THREAD

**Issue by LittleNightmare** [AtmoOmen/DailyRoutines#54]
只有石之家的配置保存正确，目前fflogs与贴吧的会修改石之家的保存字段

https://github.com/AtmoOmen/DailyRoutines/blob/b880444bef75d7894f5de1d443e2ff27040e82e5/DailyRoutines/Modules/Interface/ExpandPlayerMenuSearch.cs#L55-L58

**Comment by AtmoOmen** [comment]
感谢指出, 已修复, 将在下版本推送

**Comment by AtmoOmen** [comment]
0.3.9.0 已推送
