### ISSUE TITLE
自动取出投影台中可放入收藏柜状态：错误取出不可放入收藏柜的部分装备

### ISSUE THREAD

**Issue by LittleNightmare** [AtmoOmen/DailyRoutines#55]
下图是错误取出的装备，我重新幻化回去的，可能哪里判断还有问题。觉得可以先写个提示之类的
![304f13abb162271b9489a0b1bfd2002e](https://github.com/AtmoOmen/DailyRoutines/assets/19811879/9b125e8a-22cd-475e-83e2-248900025a34)

**Comment by AtmoOmen** [comment]
已修复, 更改了相关数据读取方式, 下版本推送
