### ISSUE TITLE
[Feature Request][AutoLogin] 多角色支持&掉线后自动登录

### ISSUE THREAD

**Issue by A2uria** [AtmoOmen/DailyRoutines#56]
## 多角色支持

支持配置多个角色并按优先级登录，特别是支持不同大区的不同角色及支持相同大区不同角色的快速切换。

## 掉线后自动登录

准确的说是给一个能回退到老版本表现的选择，这样搭配獭爹的 NoKill 可以在妈水晶飞踢后自动登录，不用重开游戏。

当然抄个 NoKill 就更好了不过这里不考虑这个。

**Comment by AtmoOmen** [comment]
0.4.0.0 已推送
