### ISSUE TITLE
自动确认副本内物体对话框可以增加屏蔽复活提示的选项吗？

### ISSUE THREAD

**Issue by Chroen** [AtmoOmen/DailyRoutines#57]
有时候用青魔斩杀线自爆之后被队友复活，或者解限扎蛮神之后会弹回到起始点的提示框，因为秒接受所以就算点了退本按钮也会先复活再退本，很影响效率，能否增加一个“无视队友复活和回到起始点”这样的选项？

**Comment by AtmoOmen** [comment]
是一早就屏蔽的情况 请自行检查其他已安装插件
https://github.com/AtmoOmen/DailyRoutines/blob/c910dbbe102fc75928188e5f7a973c22bcf924a8/DailyRoutines/Modules/CombatExpand/AutoInDutySelectYes.cs#L49

**Comment by Chroen** [comment]
测试了一下，只开启Dailyroutines的情况下，青魔自爆后弹出回到起始点提示框，无视提示框直接点击退本，回到起始点不退本，关闭Dailyroutines则无该问题。[https://youtu.be/XYDpoD1oAxk](url)

**Comment by Chroen** [comment]
测试了一下，全程关闭AlreadyYes插件（自检应该没有其他插件有类似功能），只开启DailyRoutines，进入副本，青魔自爆后弹出回到起始点提示框，无视提示框点击退本按钮，插件确认回到起始点，没有退本。
关闭DailyRoutines，点击退本，手动二次确认，正常退本没有问题。
是不是两个对话框堆叠在一起导致插件没法判断应该确认哪个？
附视频 https://youtu.be/XYDpoD1oAxk
