### ISSUE TITLE
是否能添加自动处理潜水艇垃圾的功能

### ISSUE THREAD

**Issue by IceFairy520** [AtmoOmen/DailyRoutines#66]
例如oj会带回来的红宝石、星红石、蓝宝石、星蓝石、祖母绿、钻石、黄金锭等，通常收完艇这些垃圾都要在雇员那一个个点委托雇员出售物品，又或者一个个拖出去舍弃，如果堆着不处理过两天就会占两三排背包

**Comment by LeiSangSang** [comment]
![Uploading Snipaste_2024-04-22_12-05-16.png…]()

**Comment by LeiSangSang** [comment]
![Snipaste_2024-04-22_12-05-16](https://github.com/AtmoOmen/DailyRoutines/assets/63998077/422a0819-d7a4-4e66-8bd5-bc7b34f84ee7)

**Comment by AtmoOmen** [comment]
已添加 下个版本推送
