### ISSUE TITLE
改价功能会导致死锁

### ISSUE THREAD

**Issue by PaleNutcrackers** [AtmoOmen/DailyRoutines#71]
如果被改价的物品在市场上和交易记录里都没有价格 此时游戏会循环点开价格与历史价格后死锁 大约十多秒后游戏崩溃

**Comment by AtmoOmen** [comment]
麻烦提供相关报错日志或者录像用于确认问题真实存在, 模块是有对市场与历史记录均无的情况做处理的

https://github.com/AtmoOmen/DailyRoutines/blob/acd4c0502cdbf63e21564227ea79a5b7ef01d3a6/DailyRoutines/Modules/Retainer/AutoRetainerPriceAdjust.cs#L431-L436
