### ISSUE TITLE
想请教一下字典还有哈希表为什么可以这样初始化

### ISSUE THREAD

**Issue by Jupyter2339** [AtmoOmen/DailyRoutines#8]
```private static Dictionary<uint, (string, uint)> LeveQuests = [];```
    ```private static readonly HashSet<uint> QualifiedLeveCategories = [9, 10, 11, 12, 13, 14, 15, 16];```
在VS2022中会报如图的错误，想知道您是怎么解决的，因为我一般初始化是用new来初始化
![屏幕截图 2024-02-12 160322](https://github.com/AtmoOmen/DailyRoutines/assets/142524310/8610e3dd-7c31-45a4-87be-d342a5da4406)
，但是您这里好多是用这种方法初始化的，想知道要如何解决报错，谢谢您

**Comment by Jupyter2339** [comment]
> 详见这里: https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/operators/collection-expressions

原来如此，谢谢您的回复，那么为什么我的VS还是会报错呢TT

**Comment by AtmoOmen** [comment]
> > > > 详见这里: https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/operators/collection-expressions
> > > 
> > > 
> > > 原来如此，谢谢您的回复，那么为什么我的VS还是会报错呢TT
> > 
> > 
> > 自行检查版本：https://learn.microsoft.com/zh-cn/dotnet/csharp/whats-new/csharp-12
> 
> 草还真是，太感谢A佬了TT，顺便问一下A佬用的是Ap8的哪个版本，我用国服最新的那个XIVLaucherCN的dev库看了一下貌似Dalamud.Interface.Utility这个库没有了，搜了一下文档说是移除了TT ![image](https://private-user-images.githubusercontent.com/142524310/304399580-21d2d131-dab8-4b87-a04a-e75d5dd32a03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjkwODcsIm5iZiI6MTcwNzgyODc4NywicGF0aCI6Ii8xNDI1MjQzMTAvMzA0Mzk5NTgwLTIxZDJkMTMxLWRhYjgtNGI4Ny1hMDRhLWU3NWQ1ZGQzMmEwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMjUzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjk2MjRmNjU1ZWY2YjEzN2JlMjZkYzE0Zjg3MTdhZWUyM2UxOTFhYzhjZDVlZDZkMDQ3ZjBjMTMxMjcxNjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9I7Uti8vGSCnPTI_94MPZRx2z7DackAYKbrvZIfhTbA)

我用于开发的依赖就只是 XIVLauncherCN 下自带的 lib。至于 ImGuiHelpers，一直存在，API 9 也只是移动了位置，未被移除。
API 8: https://github.com/ottercorp/Dalamud/blob/master/Dalamud/Interface/ImGuiHelpers.cs
API 9: https://github.com/goatcorp/Dalamud/blob/master/Dalamud/Interface/Utility/ImGuiHelpers.cs

**Comment by Jupyter2339** [comment]
> > > > > 详见这里: https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/operators/collection-expressions
> > > > 
> > > > 
> > > > 原来如此，谢谢您的回复，那么为什么我的VS还是会报错呢TT
> > > 
> > > 
> > > 自行检查版本：https://learn.microsoft.com/zh-cn/dotnet/csharp/whats-new/csharp-12
> > 
> > 
> > 草还真是，太感谢A佬了TT，顺便问一下A佬用的是Ap8的哪个版本，我用国服最新的那个XIVLaucherCN的dev库看了一下貌似Dalamud.Interface.Utility这个库没有了，搜了一下文档说是移除了TT ![image](https://private-user-images.githubusercontent.com/142524310/304399580-21d2d131-dab8-4b87-a04a-e75d5dd32a03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjkwODcsIm5iZiI6MTcwNzgyODc4NywicGF0aCI6Ii8xNDI1MjQzMTAvMzA0Mzk5NTgwLTIxZDJkMTMxLWRhYjgtNGI4Ny1hMDRhLWU3NWQ1ZGQzMmEwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMjUzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjk2MjRmNjU1ZWY2YjEzN2JlMjZkYzE0Zjg3MTdhZWUyM2UxOTFhYzhjZDVlZDZkMDQ3ZjBjMTMxMjcxNjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9I7Uti8vGSCnPTI_94MPZRx2z7DackAYKbrvZIfhTbA)
> 
> 我用于开发的依赖就只是 XIVLauncherCN 下自带的 lib。至于 ImGuiHelpers，一直存在，API 9 也只是移动了位置，未被移除。 API 8: https://github.com/ottercorp/Dalamud/blob/master/Dalamud/Interface/ImGuiHelpers.cs API 9: https://github.com/goatcorp/Dalamud/blob/master/Dalamud/Interface/Utility/ImGuiHelpers.cs

草可以了T T，太感谢A佬了
