### ISSUE TITLE
[Bug][PlayerTargetInfoExpand] Target & TargetsTarget not working

### ISSUE THREAD

**Issue by A2uria** [AtmoOmen/DailyRoutines#91]
![](https://github.com/AtmoOmen/DailyRoutines/assets/83493416/8c7c9350-cc82-4437-8876-5b46d3472484)

![](https://github.com/AtmoOmen/DailyRoutines/assets/83493416/abe342cf-4930-4f14-9cc8-8730ead53237)

bug 应该跟副本和队伍内外玩家目标无关。

**Comment by AtmoOmen** [comment]
本地无法复现, 请检查无法生效时 `/xllog` 内是否有相关报错日志, 如没有, 可能为与其他插件的兼容性问题

**Comment by A2uria** [comment]
bug 跟目标情报分别显示有关，关闭目标情报分别显示可复现。

提了个 pr：https://github.com/AtmoOmen/DailyRoutines/pull/102

**Comment by A2uria** [comment]
自身目标延迟更新的问题还在。
