### ISSUE TITLE
希望给自动雇员改价单独加个开关

### ISSUE THREAD

**Issue by zdian** [AtmoOmen/DailyRoutines#97]
开了自动雇员就强行自动改价很不方便。
另外操作延迟设置不起效，设置了还是秒改。

**Comment by AtmoOmen** [comment]
请使用打断热键

**Comment by zdian** [comment]
> 请使用打断热键

试了下，操作有点极限，点出售的瞬间就要按，慢一点他就自动挂上去了。

不能像其他功能一样点开始才修改吗？

**Comment by AtmoOmen** [comment]
> > 请使用打断热键
> 
> 试了下，操作有点极限，点出售的瞬间就要按，慢一点他就自动挂上去了。
> 
> 不能像其他功能一样点开始才修改吗？

在开始前就按住即可
